name: Push Success Message

on:
  push:

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display success message
        run: echo "✅ Code pushed successfully! GitHub Action ran without errors."
